//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatableCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produk
    {
        public int Idproduk { get; set; }
        public string nama_produk { get; set; }
        public int harga_produk { get; set; }
        public string deskripsi { get; set; }
    }
}
